routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\PermisstionController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RequestController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Models\HistoryRequestModel;
use GuzzleHttp\Psr7\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('login', [AuthController::class, 'login'])->name('login');
Route::post('login', [AuthController::class, 'logon'])->name('logon');
Route::get('logout', [AuthController::class, 'logout'])->name('logout');
Route::get('regiter', [AuthController::class, 'regiter'])->name('regiter');
Route::get('forgot-password', [AuthController::class, 'forgotPassword'])->name('forgot.password');
Route::get('first-login', [AuthController::class, 'firstLogin'])->name('first.login');
Route::put('first-logon', [AuthController::class, 'firstLogon'])->name('first.logon');
Route::post('forgot_password/check_email',[AuthController::class, 'checkEmail'])->name('check.email');
Route::get('changePassword',[AuthController::class, 'changePassword'])->name('change.password');
Route::put('do-changePassword',[AuthController::class, 'doChangePassword'])->name('do.change.password');

Route::delete('requests/delete/{id}', [RequestController::class,'delete'])->name('delete.request')->middleware(['auth']);
Route::resource('requests', RequestController::class)->middleware(['auth']);

Route::prefix('dashboard')->middleware(['auth','first.login'])->group(function () {
    Route::get('/',[AuthController::class, 'index'])->name('dashboard');
    Route::get('Danh-sach-nhan-vien', [UserController::class, 'list'])->name('users.list');
    Route::get('Danh-sach-nhan-vien/{id}', [UserController::class, 'infomation'])->name('users.info');
    Route::get('user-view-product', [ProductController::class, 'userView'])->name('user.view.product');
    Route::get('user-list-request', [RequestController::class, 'userList'])->name('user.list.request');
    Route::put('request-solved', [RequestController::class, 'requestSolved'])->name('request.solved');
    Route::put('request-export', [RequestController::class, 'requestExport'])->name('request.export');
    Route::put('request-return', [RequestController::class, 'requestReturn'])->name('request.return');
    Route::put('do-export', [RequestController::class, 'doExport'])->name('do.export');
    Route::put('do-return', [RequestController::class, 'doReturn'])->name('do.return');
    Route::put('request-refuse', [RequestController::class, 'requestRefuse'])->name('request.refuse');
    Route::resource('products', ProductController::class);
    Route::middleware(['can:is-admin'])->group(function () {
        Route::resource('categories', CategoryController::class);
        Route::resource('users', UserController::class);
        Route::resource('departments', DepartmentController::class);
        Route::resource('roles', RoleController::class);
        Route::resource('permisstions', PermisstionController::class)->only(['index', 'create' , 'store', 'destroy']);
        Route::resource('history-requestModels', HistoryRequestModel::class)->names('history.requests');
    }); 
});

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\RoleStoreRequest;
use App\Http\Requests\RoleUpdateRequest;
use App\Models\PermisstionModel;
use App\Models\RoleModel;
use Illuminate\Http\Request;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    private $role; 
    private $permisstion; 
    public function __construct(RoleModel $role, PermisstionModel $permisstion)
    {
        $this->role = $role;
        $this->permisstion = $permisstion;
    }
    public function index()
    {
        // $this->authorize('role.index');
        $roles= $this->role->list();
        return view('admin.roles.index',[
            'title' => 'Danh sách role',
            'roles' => $roles
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('role.create');
        $permisstions = $this->permisstion->list();
        return view('admin.roles.create',[
            'title' => 'Tạo role',
            'permisstions' => $permisstions
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RoleStoreRequest $request)
    {
        $this->authorize('role.create');
        $this->role->createRole($request);
        return redirect()->back()->with('success','Thêm thành công role :'.$request->name);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {   
        $this->authorize('role.update');
        $role = $this->role->find($id);
        $permisstions = $this->permisstion->list();
        return view('admin.roles.update',[
            'title' => 'Edit role',
            'permisstions' => $permisstions,
            'role' => $role
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function update(RoleUpdateRequest $request,$id)
    {
        $this->authorize('role.update');
        $this->role->updateRole($request, $id);
        return redirect()->back()->with('success','Sửa thành công role :'.$request->name);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->authorize('role.delete');
        $this->role->deleteRole($id);
        return redirect()->back()->with('success','Xóa thành công role');
    }
}

resources/views/admin/roles/create.blade.php
@extends('admin.layouts.main')
@section('css')
    <link rel="stylesheet" href="{{ asset('adminlte\style\roles\role.css') }}">
@endsection
@section('js')
<script src="{{ asset('adminlte\style\roles\role.js') }}"></script>
@endsection
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
    <li class="breadcrumb-item active"><a href="{{ route('roles.index') }}">Danh sách roles</a></li>
    <li class="breadcrumb-item active"><a href="#">Thêm role</a></li>
@endsection
@section('content')
    {{-- <div class="formAdd row justify-content-center col-12" > --}}
    <div class="col-12 box-bety">
        @include('admin.layouts.alert')
        <form action="{{ route('roles.store') }}" method="post">
            @csrf
            <div class="form-group">
                <label for="name">role Name</label>
                <input type="text" name="name" id="name" value="{{ old('name') }}" class="form-control"
                    placeholder="Nhập tên role...">
            </div>
            <div class="col-12 row">
                <div class="col-12">
                    <label for="">
                        <input id="checkall" type="checkbox" class="checkall" id="" value=""> &ensp;
                        <label for="checkall"> Check All</label>
                    </label>
                </div>
                @foreach ($permisstions as $permisstion)
                    <div class="card border-primary mb-3 col-12">
                        <div class="card-header">
                            <div >
                                <input type="checkbox" class="parentPer" id="" value=""> &ensp;
                                <span class="back">Chức năng : &ensp;<b>{{ ucfirst($permisstion->name) }}</b></h5>  
                            </div>
                        </div>
                        <hr>
                        <div class="card-body row">
                            @foreach ($permisstion->childs as $child)
                                <div class="col-3">
                                    <span class="card-title">
                                        <input type="checkbox" class="chilPer" name="child[]" id=""
                                            value="{{ $child->id }}">&ensp;
                                        <label for="">
                                           <small> {{ $child->name }}</small>
                                        </label>
                                    </span>
                                </div>
                            @endforeach
                        </div>
                    </div>
                @endforeach
            </div>
            <button type="submit" class="btn btn-sm btn-primary">Thêm Role</button>
        </form>
    </div>
    {{-- </div> --}}
@endsection

resources/views/admin/roles/index.blade.php
@extends('admin.layouts.main')
@section('css')
@endsection
@section('js')
@endsection
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
    <li class="breadcrumb-item"><a href="{{ route('roles.index') }}">Danh sách Role</a></li>
@endsection
@section('content')
    <div class="col-12 box-bety">
        @can('role.create')
        <a href="{{ route('roles.create') }}" class="btn button btn-sm btn-primary" style="float: right">Thêm Role</a>
        @endcan
        <div class="col-10">@include('admin.layouts.alert')</div>
        <table class="table table-light table-hover">
            <thead class="thead-light">
                <tr>
                    <th width=5%>STT</th>
                    <th>Tên Roles</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($roles as $key => $role)
                    <tr>
                        <td>{{ $key + 1 }}</td>
                        <td>{{ $role->name }}</td>
                        <td>
                            <div class="row">
                                @can('role.update')
                                <a href="{{ route('roles.edit', $role->id) }}" class="btn button btn-warning"><i
                                    class="fa fa-edit"></i></a> &ensp;
                                @endcan
                                @can('role.delete')
                                <form action="{{ route('roles.destroy', $role->id) }}" method="post">
                                    @csrf
                                    @method('delete')
                                    <button type="submit" class="btn button btn-danger" onclick="return confirm('Are you sure?')">
                                        <i class="fa fa-trash"></i></button>
                                </form>
                                @endcan
                            </div>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
@endsection

resources/views/admin/roles/update.blade.php
@extends('admin.layouts.main')
@section('css')
    <link rel="stylesheet" href="{{ asset('adminlte\style\roles\role.css') }}">
@endsection
@section('js')
    <script src="{{ asset('adminlte\style\roles\role.js') }}"></script>
@endsection
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
    <li class="breadcrumb-item active"><a href="{{ route('roles.index') }}">Danh sách roles</a></li>
    <li class="breadcrumb-item active"><a href="#">Sửa role</a></li>
@endsection
@section('content')
    {{-- <div class="formAdd row justify-content-center col-12" > --}}
    <div class="col-12 box-bety">
        @include('admin.layouts.alert')
        <form action="{{ route('roles.update', $role->id) }}" method="post">
            @method('put')
            @csrf
            <div class="form-group">
                <label for="name">role Name</label>
                <input type="text" name="name" id="name" value="{{ $role->name }}" class="form-control"
                    placeholder="Nhập tên role...">
                <input class="form-control" type="hidden" name="id" value="{{ $role->id }}">
            </div>
            <div class="col-12 row">
                <div class="col-12">
                    <label for="">
                        <input id="checkall" type="checkbox" class="checkall" id="" value=""> &ensp;
                        <label for="checkall"> Check All</label>
                    </label>
                </div>
                @foreach ($permisstions as $permisstion)
                    <div class="card border-primary mb-3 col-12">
                        <div class="card-header">
                            <div>
                                <input type="checkbox" class="parentPer" id="" value=""> &ensp;
                                <span class="back">Chức năng : &ensp;<b>{{ ucfirst($permisstion->name) }}</b></h5>
                            </div>
                        </div>
                        <hr>
                        <div class="card-body row">
                            @foreach ($permisstion->childs as $child)
                                <div class="col-3">
                                    <span class="card-title">
                                        <input type="checkbox" class="chilPer" name="child[]" id=""
                                            value="{{ $child->id }}"
                                            {{$role->permisstions->contains('id',$child->id) ? 'checked':''}}
                                            >&ensp;
                                        <label for="">
                                            <small> {{ $child->name }}</small>
                                        </label>
                                    </span>
                                </div>
                            @endforeach
                        </div>
                    </div>
                @endforeach
            </div>
            <button type="submit" class="btn btn-sm btn-primary">Sửa Role</button>
        </form>
    </div>
    {{-- </div> --}}
@endsection