routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\PermisstionController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RequestController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Models\HistoryRequestModel;
use GuzzleHttp\Psr7\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('login', [AuthController::class, 'login'])->name('login');
Route::post('login', [AuthController::class, 'logon'])->name('logon');
Route::get('logout', [AuthController::class, 'logout'])->name('logout');
Route::get('regiter', [AuthController::class, 'regiter'])->name('regiter');
Route::get('forgot-password', [AuthController::class, 'forgotPassword'])->name('forgot.password');
Route::get('first-login', [AuthController::class, 'firstLogin'])->name('first.login');
Route::put('first-logon', [AuthController::class, 'firstLogon'])->name('first.logon');
Route::post('forgot_password/check_email',[AuthController::class, 'checkEmail'])->name('check.email');
Route::get('changePassword',[AuthController::class, 'changePassword'])->name('change.password');
Route::put('do-changePassword',[AuthController::class, 'doChangePassword'])->name('do.change.password');

Route::delete('requests/delete/{id}', [RequestController::class,'delete'])->name('delete.request')->middleware(['auth']);
Route::resource('requests', RequestController::class)->middleware(['auth']);

Route::prefix('dashboard')->middleware(['auth','first.login'])->group(function () {
    Route::get('/',[AuthController::class, 'index'])->name('dashboard');
    Route::get('Danh-sach-nhan-vien', [UserController::class, 'list'])->name('users.list');
    Route::get('Danh-sach-nhan-vien/{id}', [UserController::class, 'infomation'])->name('users.info');
    Route::get('user-view-product', [ProductController::class, 'userView'])->name('user.view.product');
    Route::get('user-list-request', [RequestController::class, 'userList'])->name('user.list.request');
    Route::put('request-solved', [RequestController::class, 'requestSolved'])->name('request.solved');
    Route::put('request-export', [RequestController::class, 'requestExport'])->name('request.export');
    Route::put('request-return', [RequestController::class, 'requestReturn'])->name('request.return');
    Route::put('do-export', [RequestController::class, 'doExport'])->name('do.export');
    Route::put('do-return', [RequestController::class, 'doReturn'])->name('do.return');
    Route::put('request-refuse', [RequestController::class, 'requestRefuse'])->name('request.refuse');
    Route::resource('products', ProductController::class);
    Route::middleware(['can:is-admin'])->group(function () {
        Route::resource('categories', CategoryController::class);
        Route::resource('users', UserController::class);
        Route::resource('departments', DepartmentController::class);
        Route::resource('roles', RoleController::class);
        Route::resource('permisstions', PermisstionController::class)->only(['index', 'create' , 'store', 'destroy']);
        Route::resource('history-requestModels', HistoryRequestModel::class)->names('history.requests');
    }); 
});

resources/views/admin/layouts/alert.blade.php
<div style="padding-top: 0.5rem ">
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
@if(Session::has('error'))
    <div class="alert alert-danger">
        {{Session::get('error')}}
    </div>
@endif
@if(Session::has('success'))
    <div class="alert alert-success">
        {{Session::get('success')}}
    </div>
@endif

</div>

resources/views/admin/layouts/breadcrumb.blade.php
<li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
<li class="breadcrumb-item active"><a href="javascript:void(0)"></a></li>

resources/views/admin/layouts/header.blade.php
<div class="nav-header">
    <a href="{{ route('dashboard') }}" class="brand-logo">
        <img class="logo-abbr" src="  {{ asset('uploads/logo.png') }}" alt="">
        <img class="logo-compact" src="  {{ asset('adminlte/images/logo-text.png') }}" alt="">
        <img class="brand-title" src="  {{ asset('uploads/logo.png') }}" alt="">
    </a>

    <div class="nav-control">
        <div class="hamburger">
            <span class="line"></span><span class="line"></span><span class="line"></span>
        </div>
    </div>
</div>

<div class="header">
    <div class="header-content">
        <nav class="navbar navbar-expand">
            <div class="collapse navbar-collapse justify-content-between">
                <div class="header-left">
                    <div class="search_bar dropdown">
                        <span class="search_icon p-3 c-pointer" data-toggle="dropdown">
                            <i class="mdi mdi-magnify"></i>
                        </span>
                        <div class="dropdown-menu p-0 m-0">
                            <form>
                                <input class="form-control" type="search" value="{{ request()->search }}" name="search" placeholder="Search" aria-label="Search">
                            </form>
                        </div>
                    </div>
                </div>

                <ul class="navbar-nav header-right">
                    <li class="nav-item dropdown notification_dropdown">
                        <a class="nav-link" href="#" role="button" data-toggle="dropdown">
                            <i class="mdi mdi-bell"></i>
                            <div class="pulse-css"></div>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <ul class="list-unstyled">
                                <li class="media dropdown-item">
                                    <span class="success"><i class="ti-user"></i></span>
                                    <div class="media-body">
                                        <a href="#">
                                            <p><strong>Martin</strong> has added a <strong>customer</strong>
                                                Successfully
                                            </p>
                                        </a>
                                    </div>
                                    <span class="notify-time">3:20 am</span>
                                </li>
                                <li class="media dropdown-item">
                                    <span class="primary"><i class="ti-shopping-cart"></i></span>
                                    <div class="media-body">
                                        <a href="#">
                                            <p><strong>Jennifer</strong> purchased Light Dashboard 2.0.</p>
                                        </a>
                                    </div>
                                    <span class="notify-time">3:20 am</span>
                                </li>
                                <li class="media dropdown-item">
                                    <span class="danger"><i class="ti-bookmark"></i></span>
                                    <div class="media-body">
                                        <a href="#">
                                            <p><strong>Robin</strong> marked a <strong>ticket</strong> as
                                                unsolved.
                                            </p>
                                        </a>
                                    </div>
                                    <span class="notify-time">3:20 am</span>
                                </li>
                                <li class="media dropdown-item">
                                    <span class="primary"><i class="ti-heart"></i></span>
                                    <div class="media-body">
                                        <a href="#">
                                            <p><strong>David</strong> purchased Light Dashboard 1.0.</p>
                                        </a>
                                    </div>
                                    <span class="notify-time">3:20 am</span>
                                </li>
                                <li class="media dropdown-item">
                                    <span class="success"><i class="ti-image"></i></span>
                                    <div class="media-body">
                                        <a href="#">
                                            <p><strong> James.</strong> has added a<strong>customer</strong>
                                                Successfully
                                            </p>
                                        </a>
                                    </div>
                                    <span class="notify-time">3:20 am</span>
                                </li>
                            </ul>
                            <a class="all-notification" href="#">See all notifications <i
                                    class="ti-arrow-right"></i></a>
                        </div>
                    </li>
                    <li class="nav-item dropdown header-profile">
                        <a class="nav-link" href="#" role="button" data-toggle="dropdown">
                            <small>{{ Auth::user()->name ?? ""}}</small>
                            <i class="mdi mdi-account"></i> 
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            {{-- <a href="app-profile.html" class="dropdown-item">
                                <i class="icon-user"></i>
                                <span class="ml-2">Profile </span>
                            </a> --}}
                            <a href="{{ route('logout') }}" class="dropdown-item">
                                <i class="icon-key"></i>
                                <span class="ml-2">Logout </span>
                            </a>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</div>

resources/views/admin/layouts/main.blade.php
<!DOCTYPE html>
<html lang="en">


<!-- Mirrored from demo.themefisher.com/focus/chart-chartist.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 04 Apr 2022 18:13:07 GMT -->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>{{ $title ?? 'Trang chủ' }} </title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('adminlte/images/favicon.png') }}">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,800" rel="stylesheet" />
    <link rel="stylesheet" href="{{ asset('adminlte/vendor/chartist/css/chartist.min.css') }}">
    <link href="{{ asset('fontawesome/css/all.css') }}" rel="stylesheet">
    <link href="{{ asset('adminlte/css/style.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('adminlte/css/my_css.css') }}">
    @yield('css')
</head>

<body>
    <div id="main-wrapper">

        @include('admin.layouts.header')

        @include('admin.layouts.sidebar')

        <div class="content-body" style="min-heag">
            <div class="container-fluid" style="min-height: 700px;">
                <div class="row page-titles mx-0 top-bety">
                    <div class="col-sm-6">
                        <div class="welcome-text">
                            <h4>{{ $topTitle ?? ($title ?? 'Trang chủ') }}</h4>
                        </div>
                    </div>
                    <div class="col-sm-6 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                        <ol class="breadcrumb">
                            @yield('breadcrumb')
                        </ol>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="row">
                            @yield('content')
                        </div>
                    </div>

                </div>
            </div>
            <!--**********************************
            Content body end
        ***********************************-->


            <!--**********************************
            Footer start
        ***********************************-->
            <div class="footer" style="margin-top:10em">
                <div class="copyright">
                    <p>Copyright © Designed &amp; Developed by <a href="#" target="_blank">Quixkit</a> 2019</p>
                </div>
            </div>
            <!--**********************************
            Footer end
        ***********************************-->

            <!--**********************************
           Support ticket button start
        ***********************************-->

            <!--**********************************
           Support ticket button end
        ***********************************-->


        </div>
        <!--**********************************
        Main wrapper end
    ***********************************-->

        <!--**********************************
        Scripts
    ***********************************-->
        <!-- Required vendors -->
        <script src=" {{ asset('adminlte/vendor/global/global.min.js') }} "></script>
        <script src=" {{ asset('adminlte/js/quixnav-init.js') }} "></script>
        <script src=" {{ asset('adminlte/js/custom.min.js') }} "></script>
        <script src=" {{ asset('fontawesome/js/fontawesome.js') }} "></script>


        <!-- Chart Chartist plugin files -->
        <script src=" {{ asset('adminlte/vendor/chartist/js/chartist.min.js') }} "></script>
        <script src=" {{ asset('adminlte/vendor/chartist-plugin-tooltips/js/chartist-plugin-tooltip.min.js') }} "></script>
        <script src=" {{ asset('adminlte/js/plugins-init/chartist-init.js') }} "></script>
        @yield('js')
</body>
{{-- {{ asset('adminlte/') }} --}}

<!-- Mirrored from demo.themefisher.com/focus/chart-chartist.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 04 Apr 2022 18:13:09 GMT -->

</html>

resources/views/admin/layouts/sidebar.blade.php
<div class="quixnav">
    <div class="quixnav-scroll">
        <ul class="metismenu" id="menu">
            @can('is-admin')
                <li class="nav-label first">Main Menu</li>
                @can('category.index')
                    <li><a class="has-arrow" href="javascript:void()" aria-expanded="false"><i
                                class="fal fa-tachometer-alt-slowest"></i><span class="nav-text">Danh mục</span></a>
                        <ul aria-expanded="false">
                            <li><a href="{{ route('categories.index') }}">Danh sách danh mục</a></li>
                            @can('category.create')
                                <li><a href="{{ route('categories.create') }}">Create Category</a></li>
                            @endcan
                        </ul>
                    </li>
                @endcan
                @can('product.index')
                    <li><a class="has-arrow" href="javascript:void()" aria-expanded="false"><i
                                class="fal fa-tachometer-alt-fastest"></i><span class="nav-text">Sản phẩm</span></a>
                        <ul aria-expanded="false">
                            <li><a href="{{ route('products.index') }}">Danh sách sản phẩm </a></li>
                            @can('product.create')
                                <li><a href="{{ route('products.create') }}">Tạo sản phẩm</a></li>
                            @endcan
                        </ul>
                    </li>
                @endcan
                <li><a class="has-arrow" href="javascript:void()" aria-expanded="false"><i class="fas fa-user-tie"></i><span class="nav-text">Danh sách nhân viên</span></a>
                    <ul aria-expanded="false">
                        <li><a href="{{ route('users.list') }}">Danh sách </a></li>
                    </ul>
                </li>
                @can('request.index')
                    <li class="nav-label">Yêu cầu</li>
                    <li><a class="has-arrow" href="javascript:void()" aria-expanded="false"><i
                                class="fal fa-folder-tree"></i><span class="nav-text">Danh sách yêu cầu</span></a>
                        <ul aria-expanded="false">
                            <li><a href="{{ route('requests.index') }}?status={{ requestPending }}">Chờ phê duyệt</a>


                            <li><a
                                    href="{{ route('requests.index') }}?status={{ requestSolved }}&ex_action={{ requestExported }}&ex_action1={{ returned }} ">Đã
                                    duyệt</a>
                            </li>
                            <li><a
                                    href="{{ route('requests.index') }}?ex_action={{ requestDefault }}&ex_action1={{ requestExport }}   ">Đã
                                    xuất sản
                                    phẩm</a>
                            </li>
                            <li><a href="{{ route('requests.index') }}?status={{ returned }} ">Sản phẩm đã trả</a>
                            </li>
                            <li><a href="{{ route('requests.index') }}?status={{ requestRefuse }}">Đã bị từ chối</a>
                            </li>
                            <li><a href="{{ route('requests.index') }}">Tất cả Yêu cầu </a></li>
                    </li>

                </ul>
                </li>
            @endcan
            @can('user.index')
                <li class="nav-label">Setting</li>
                <li><a class="has-arrow" href="javascript:void()" aria-expanded="false"><i class="fal fa-users"></i><span
                            class="nav-text">Tài khoản</span></a>
                    <ul aria-expanded="false">



                        <li><a href="{{ route('users.index') }}">Danh sách tài khoản</a></li>

                        @can('user.create')
                            <li><a href="{{ route('users.create') }}">Tạo tài khoản </a></li>
                        @endcan
                    </ul>
                </li>
            @endcan
            @can('department.index')
                <li><a class="has-arrow" href="javascript:void()" aria-expanded="false"><i class="far fa-building"></i><span
                            class="nav-text">Phòng ban</span></a>
                    <ul aria-expanded="false">

                        <li><a href="{{ route('departments.index') }}">Danh sách phòng ban </a></li>

                        @can('department.create')
                            <li><a href="{{ route('departments.create') }}">Tạo phòng ban</a></li>
                        @endcan
                    </ul>
                </li>
            @endcan
            @can('role.index')
                <li><a class="has-arrow" href="javascript:void()" aria-expanded="false"><i class="fas fa-user-cog"></i><span
                            class="nav-text">Roles</span></a>
                    <ul aria-expanded="false">
                        <li><a href="{{ route('roles.index') }}">Danh sách Role </a></li>

                        @can('role.create')
                            <li><a href="{{ route('roles.create') }}">Tạo Role</a></li>
                        @endcan
                    </ul>
                </li>
            @endcan
            @can('permisstion.index')
                <li><a class="has-arrow" href="javascript:void()" aria-expanded="false"><i class="fas fa-cogs"></i><span
                            class="nav-text">Pemisstions</span></a>
                    <ul aria-expanded="false">



                        <li><a href="{{ route('permisstions.index') }}">Danh sách Permisstion </a></li>

                    </ul>
                </li>
            @endcan
        @endcan


        @can('is-user', typeUser)
            <li class="nav-label">Dashboard</li>
            <li><a class="has-arrow" href="javascript:void()" aria-expanded="false"><i class="icon icon-app-store"></i><span
                        class="nav-text">Người dùng</span></a>
                <ul aria-expanded="false">
                    <li><a href="{{ route('user.view.product') }} ">Danh sách sản phẩm</a></li>
                    <li><a class="has-arrow" href="javascript:void()" aria-expanded="false">Yêu cầu của tôi</a>
                        <ul aria-expanded="false">
                            <li><a href="{{ route('user.list.request') }}?status={{ requestPending }}">Yêu cầu đang
                                    chờ</a></li>
                            <li><a
                                    href="{{ route('user.list.request') }}?status={{ requestSolved }}&ex_action={{ requestExported }}&ex_action1={{ returned }}  ">Yêu
                                    cầu đã duyệt</a></li>
                            <li><a
                                    href="{{ route('user.list.request') }}?ex_action={{ requestDefault }}&ex_action1={{ requestExport }}  ">Yêu
                                    cầu đã xuất
                                    sản phẩm</a></li>
                            <li><a href="{{ route('user.list.request') }}?status={{ returned }} ">Yêu cầu đã trả
                                    lại</a></li>
                            <li><a href="{{ route('user.list.request') }}?status={{ requestRefuse }}">Yêu cầu bị từ
                                    chối</a></li>
                            <li><a href="{{ route('user.list.request') }} ">Tất cả yêu cầu</a></li>
                            <li>
                        </ul>
                    </li>
                </ul>
            </li>
        @endcan

        </ul>
    </div>


</div>