routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\PermisstionController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RequestController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Models\HistoryRequestModel;
use GuzzleHttp\Psr7\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('login', [AuthController::class, 'login'])->name('login');
Route::post('login', [AuthController::class, 'logon'])->name('logon');
Route::get('logout', [AuthController::class, 'logout'])->name('logout');
Route::get('regiter', [AuthController::class, 'regiter'])->name('regiter');
Route::get('forgot-password', [AuthController::class, 'forgotPassword'])->name('forgot.password');
Route::get('first-login', [AuthController::class, 'firstLogin'])->name('first.login');
Route::put('first-logon', [AuthController::class, 'firstLogon'])->name('first.logon');
Route::post('forgot_password/check_email',[AuthController::class, 'checkEmail'])->name('check.email');
Route::get('changePassword',[AuthController::class, 'changePassword'])->name('change.password');
Route::put('do-changePassword',[AuthController::class, 'doChangePassword'])->name('do.change.password');

Route::delete('requests/delete/{id}', [RequestController::class,'delete'])->name('delete.request')->middleware(['auth']);
Route::resource('requests', RequestController::class)->middleware(['auth']);

Route::prefix('dashboard')->middleware(['auth','first.login'])->group(function () {
    Route::get('/',[AuthController::class, 'index'])->name('dashboard');
    Route::get('Danh-sach-nhan-vien', [UserController::class, 'list'])->name('users.list');
    Route::get('Danh-sach-nhan-vien/{id}', [UserController::class, 'infomation'])->name('users.info');
    Route::get('user-view-product', [ProductController::class, 'userView'])->name('user.view.product');
    Route::get('user-list-request', [RequestController::class, 'userList'])->name('user.list.request');
    Route::put('request-solved', [RequestController::class, 'requestSolved'])->name('request.solved');
    Route::put('request-export', [RequestController::class, 'requestExport'])->name('request.export');
    Route::put('request-return', [RequestController::class, 'requestReturn'])->name('request.return');
    Route::put('do-export', [RequestController::class, 'doExport'])->name('do.export');
    Route::put('do-return', [RequestController::class, 'doReturn'])->name('do.return');
    Route::put('request-refuse', [RequestController::class, 'requestRefuse'])->name('request.refuse');
    Route::resource('products', ProductController::class);
    Route::middleware(['can:is-admin'])->group(function () {
        Route::resource('categories', CategoryController::class);
        Route::resource('users', UserController::class);
        Route::resource('departments', DepartmentController::class);
        Route::resource('roles', RoleController::class);
        Route::resource('permisstions', PermisstionController::class)->only(['index', 'create' , 'store', 'destroy']);
        Route::resource('history-requestModels', HistoryRequestModel::class)->names('history.requests');
    }); 
});

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserStoreRequest;
use App\Http\Requests\UserUpdateRequest;
use Illuminate\Http\Request;
use App\Models\UserModel;
use App\Models\DepartmentModel;
use App\Models\RoleMode;
use App\Models\RoleModel;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    private $user;
    private $department;
    private $role;
    public function __construct(UserModel $user,DepartmentModel $department,RoleModel $role){
        $this->user = $user;
        $this->department = $department;
        $this->role = $role;
    }
    public function index()
    {
        $this->authorize('user.index');
        $users = $this->user->list();
        return view('admin.users.index',[
            'title' => 'Danh sách nhân viên',
            'topTitle' => 'Danh sách nhân viên ('.$users->count().')',
            'users' => $users
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('user.create');
        $departments = $this->department::all();
        $roles = $this->role->all();
        return view('admin.users.create', [
            'title' => 'Tạo tài khoản',
            'topTile' => 'Tạo tài khoản',
            'departments' => $departments,
            'roles' => $roles
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserStoreRequest $request)
    {
        $this->authorize('user.create');
        $this->user->createUser($request);
        return redirect()->back()->with('success', 'Tạo thành công thành viên');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->authorize('user.update');
        $user = $this->user->find($id);
        $roles = $this->role->all();
        $departments = $this->department::all();
        return view('admin.users.Update', [
            'title' => 'Sửa tài khoản',
            'topTitle' => 'Sửa tài khoản : '.$user->name,
            'departments' => $departments,
            'user' => $user,
            'roles' => $roles
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserUpdateRequest $request, $id)
    {
        $this->authorize('user.update');
        $this->user->updateUser($request, $id);
        return redirect()->back()->with('success', 'Sửa thành công thành viên');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->authorize('user.delete');
        if( $this->user->deleteUser($id)){
            return redirect(route('users.index'))->with('success','Đã xóa thành công');
        }
        return redirect()->back()->with('error','có lỗi trong qá trình xóa vui lòng liên hệ với quản trị viên');
    }
    public function list()
    {
        $this->authorize('user.index');
        $users = $this->user->listUser();
        return view('admin.users.list', [
            'title' => 'Danh sách nhân viên',
            'users' => $users
        ]);

    }

    public function infomation($id)
    {
        $this->authorize('user.index');
        $user = $this->user->findById($id);
        return view('admin.users.infomation', [
            'title' => 'Chi tiết nhân viên : '. $user->name,
            'user' => $user
        ]);

    }
}

resources/views/admin/users/create.blade.php
@extends('admin.layouts.main')
@section('css')
    <link rel="stylesheet" href="{{ asset('adminlte\style\user\select2.min.css') }}">
@endsection
@section('js')
    <script src="{{ asset('adminlte\style\user\user.js') }}"></script>
    <script src="{{ asset('adminlte\style\user\select2.min.js') }}"></script>
@endsection
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
    <li class="breadcrumb-item "><a href="{{ route('users.index') }}">Danh sách tài khoản</a></li>
    <li class="breadcrumb-item active">Tạo tài khoản </li>
@endsection
@section('content')
    <div class="col-12 box-bety">
        @include('admin.layouts.alert')
        @include('admin.users.form', [
            'lable' => 'Phòng ban',
            'department' => $departments,
            'button' => 'Thêm thành viên',
            'route' => route('users.store'),
        ])
    </div>
@endsection

resources/views/admin/users/form.blade.php
<form action="{{ $route ?? route('users.update', $user->id) }}" method="Post" enctype="multipart/form-data">
    @csrf
    @method($method ?? 'post')
    <div class="form-group">
        @include('admin.components.input', [
            'name' => 'id',
            'type' => 'hidden',
            'value' => $user->id ?? '',
        ])
        @include('admin.components.label_form', [
            'label' => 'Tên đầy đủ',
            'name' => 'name',
            'placeholder' => 'Mời bạn nhập tên đầy đủ ...',
            'value' => $user->name ?? old('name'),
        ])
        @include('admin.components.label_form', [
            'label' => 'Tài khoản',
            'name' => 'user',
            'placeholder' => 'Mời bạn nhập tên tài khoản ...',
            'atribute' => isset($user) ? 'readonly' : '',
            'value' => $user->user ?? old('user'),
        ])
        @include('admin.components.label_form', [
            'label' => 'Email',
            'name' => 'email',
            'type' => 'email',
            'placeholder' => 'Mời bạn nhập email...',
            'value' => $user->email ?? old('email'),
        ])
        <div class="form-group">
            <label for="">Giới tính</label>
            <select name="gender" id="" class="form-control select2-role">
                <option {{ isset($user) && $user->gender == genderMafe ? 'selected' : '' }} value="0">Nam</option>
                <option {{ isset($user) && $user->gender == genderFemale ? 'selected' : '' }} value="1">Nữ
                </option>
            </select>
        </div>
        @include('admin.components.label_form', [
            'label' => 'Số điện thoại',
            'name' => 'phone',
            'placeholder' => 'Mời bạn nhập số điện thoại...',
            'value' => $user->phone ?? old('phone'),
        ])
        @include('admin.components.label_form', [
            'label' => 'Địa chỉ',
            'name' => 'address',
            'placeholder' => 'Mời bạn nhập địa chỉ...',
            'value' => $user->address ?? old('address'),
        ])
        @include('admin.components.select_form', [
            'label' => 'Phòng ban',
            'name' => 'department_id',
            'data' => $departments,
            'id' => $department_id ?? '',
            'class' => "form-control select2-role"
        ])

        <div class="form-group">
            <label for="">Type</label>
            <select name="type" id="" class="form-control select2-role">
                <option {{ isset($user) && $user->type == typeAdmin ? 'selected' : '' }} value="0">Hệ Thống
                </option>
                <option {{ isset($user) && $user->type == typeUser ? 'selected' : '' }} value="1">User</option>
            </select>
        </div>


        <div class="form-group">
            <label for="role">Vai trò</label>
            <select class="form-control select2-role" name="role[]" id="role" multiple>
                @foreach ($roles as $role)
                    <option value="{{ $role->id }}"  {{ isset($user) && $user->roles->contains('id',$role->id)? "selected": ""}}>{{ $role->name }}</option>
                @endforeach
            </select>
        </div>

        @include('admin.components.label_form', [
            'label' => 'Mật khẩu',
            'name' => 'password',
            'type' => 'password',
            'placeholder' => 'Mật khẩu...',
        ])

        @include('admin.components.label_form', [
            'label' => 'Nhập lại mật khẩu',
            'name' => 'password',
            'type' => 'confirm_password',
            'placeholder' => 'Nhập lại mật khẩu...',
        ])

        <div class="form-group">
            <button type="submit" class="btn btn-sm btn-primary">{{ $button }}</button>
        </div>
    </div>
</form>

resources/views/admin/users/index.blade.php
@extends('admin.layouts.main')
@section('css')
    <link rel="stylesheet" href="{{ asset('adminlte\style\user\select2.min.css') }}">
@endsection
@section('js')
    <script src="{{ asset('adminlte\style\user\user.js') }}"></script>
    <script src="{{ asset('adminlte\style\user\select2.min.js') }}"></script>
@endsection
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
    <li class="breadcrumb-item "><a href="{{ route('users.index') }}">Danh sách tài khoản</a></li>
@endsection
@section('content')
    <div class="col-12 box-bety">
        @can('user.create')
            <a href="{{ route('users.create') }}" class="btn button btn-sm btn-primary" style="float: right">Thêm tài khoản</a>
        @endcan
        @include('admin.layouts.alert')
        <table class="table table-light table-hover">
            <thead class="thead-light">
                <tr>
                    <th width=5%>STT</th>
                    <th>Tên Thành viên</th>
                    <th>User</th>
                    <th>Giới tính </th>
                    <th>Phone</th>
                    <th>Địa chỉ</th>
                    <th>Phòng ban</th>
                    <th>Loại tài khoản</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($users as $key => $user)
                    <tr>
                        <td>{{ $key + 1 }}</td>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->user }}</td>
                        <td>{{ $user->gender == genderMafe ? 'Nam' : 'Nữ' }}</td>
                        <td>{{ $user->phone }}</td>
                        <td>{{ $user->address }}</td>
                        <td><a href="?department={{ $user->department_id }}">{{ $user->department->name ?? '' }}</a></td>
                        <td>{{ $user->type == typeUser ? 'User' : 'Hệ thống' }}</td>
                        <td>
                            <div class="row">
                            
                                @can('product.update')
                                <a href="{{ route('users.edit', $user->id) }}" class="btn button btn-warning"><i
                                    class="fa fa-edit"></i></a> &ensp;
                                @endcan
                                @can('product.delete')
                                    @if (Auth::id() != $user->id)
                                        <form action="{{ route('users.destroy', $user->id) }}" method="post">
                                            @csrf
                                            @method('delete')
                                            <button type="submit" class="btn button btn-danger"
                                                onclick="return confirm('Are you sure?')">
                                                <i class="fa fa-trash"></i></button>
                                        </form>
                                    @endif
                                @endcan
                            </div>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        <div>{!! $users->appends(request()->all())->links() !!}</div>
    </div>
@endsection

resources/views/admin/users/infomation.blade.php
@extends('admin.layouts.main')
@section('css')
    <link rel="stylesheet" href="{{ asset('adminlte\style\user\select2.min.css') }}">
@endsection
@section('js')
    <script src="{{ asset('adminlte\style\user\user.js') }}"></script>
    <script src="{{ asset('adminlte\style\user\select2.min.js') }}"></script>
@endsection
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
    <li class="breadcrumb-item "><a href="{{ route('users.index') }}">Danh sách hân viên</a></li>
@endsection
@section('content')
    <div class="col-12 box-bety info">
        @include('admin.layouts.alert')
        <div class="">
            <div class="card-body center">
                <h4 class="card-title"> Nhân viên : <b>{{ $user->name }}</b></h4>
                <h6 class="card-subtitle mb-2 text-muted"> &ensp;({{ $user->user }} - {{ $user->department->name }})</h6>
            </div>
        </div>
        
        <div><b><u>Danh sách sản phẩm đang mượn</u></b></div>
        <hr>
        @if ($user->requsets->where('status', requestSolved)->whereIn('action', [requestExported, requestReturn])->count() > 0)
            <table class="table table-light table-hover">
                <thead class="thead-light">
                    <tr>
                        <th width=5%>STT</th>
                        <th>Tên sản phẩm</th>
                        <th>Mã sản phẩm</th>
                        <th>Ngày mượn</th>
                        <th>Ngày trả</th>
                        <th>Người xác nhận</th>
                        <th>Tình trạng</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($user->requsets->where('status', requestSolved)->whereIn('action', [requestExported, requestReturn]) as $key => $request)
                        <tr>
                            <td>{{ $key + 1 }}</td>
                            <td>{{ $request->product->name }}</td>
                            <td>{{ $request->product->code }}</td>
                            <td>{{ $request->brorrowed_date }}</td>
                            <td>{{ $request->date_off }}</td>
                            <td>{{ $request->history->user->name ?? '' }}</td>
                            <td>
                                <span><a class="badge button badge-outline-dark" href="?action={{ requestExported }}">Đã
                                        xuất sản phẩm </a></span>
                            <td>
                                @if ($request->action == requestReturn)
                                    <span><a class="badge button badge-outline-dark"
                                            href="#">Đang yêu cầu trả</a></span>
                                @endif
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @else
            <div style="text-align:center">Không tìm thấy yêu cầu nào...</div>
        @endif
    </div>
@endsection

resources/views/admin/users/list.blade.php
@extends('admin.layouts.main')
@section('css')
    <link rel="stylesheet" href="{{ asset('adminlte\style\user\select2.min.css') }}">
@endsection
@section('js')
    <script src="{{ asset('adminlte\style\user\user.js') }}"></script>
    <script src="{{ asset('adminlte\style\user\select2.min.js') }}"></script>
@endsection
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
    <li class="breadcrumb-item "><a href="{{ route('users.index') }}">Danh sách hân viên</a></li>
@endsection
@section('content')
    <div class="col-12 box-bety">
        @include('admin.layouts.alert')
        <table class="table table-light table-hover">
            <thead class="thead-light">
                <tr>
                    <th width=5%>STT</th>
                    <th>Tên Thành viên</th>
                    <th>User</th>
                    <th>Phòng ban</th>
                    <th>Đang mượn</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($users as $key => $user)
                    <tr>
                        <td>{{ $key + 1 }}</td>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->user }}</td>
                        <td><a href="?department={{ $user->department_id }}">{{ $user->department->name ?? '' }}</a></td>
                        <td>{{ $user->requsets->where('status', requestSolved)->whereIn('action', [requestExported, requestReturn])->count() }}</td>
                        <td>
                            <div class="row">

                                @can('user.index')
                                    <a href="{{ route('users.info', $user->id) }}" class="btn button btn-warning"><i class="far fa-info"></i></a> &ensp;
                                @endcan
                            </div>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        <div>{!! $users->appends(request()->all())->links() !!}</div>
    </div>
@endsection

resources/views/admin/users/update.blade.php
@extends('admin.layouts.main')
@section('css')
    <link rel="stylesheet" href="{{ asset('adminlte\style\user\select2.min.css') }}">
@endsection
@section('js')
    <script src="{{ asset('adminlte\style\user\user.js') }}"></script>
    <script src="{{ asset('adminlte\style\user\select2.min.js') }}"></script>
@endsection 
@section('breadcrumb')
<li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
<li class="breadcrumb-item "><a href="{{ route('users.index') }}">Danh sách tài khoản</a></li>
<li class="breadcrumb-item active">Sửa tài khoản</li>
@endsection
@section('content')
    <div class="col-12 box-bety">
        @include('admin.layouts.alert')
        @include('admin.components.input', [
            'type' => 'hidden',
            'name' => 'id',
            'value' => $user->id
        ])
        @include('admin.users.form', [
            'lable' => 'Phòng ban',
            'department' => $departments,
            'department_id' => $user->department_id,
            'button' => 'Sửa thành viên',
            'method' => 'put',
        ])
    </div>
@endsection