routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\PermisstionController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RequestController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Models\HistoryRequestModel;
use GuzzleHttp\Psr7\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('login', [AuthController::class, 'login'])->name('login');
Route::post('login', [AuthController::class, 'logon'])->name('logon');
Route::get('logout', [AuthController::class, 'logout'])->name('logout');
Route::get('regiter', [AuthController::class, 'regiter'])->name('regiter');
Route::get('forgot-password', [AuthController::class, 'forgotPassword'])->name('forgot.password');
Route::get('first-login', [AuthController::class, 'firstLogin'])->name('first.login');
Route::put('first-logon', [AuthController::class, 'firstLogon'])->name('first.logon');
Route::post('forgot_password/check_email',[AuthController::class, 'checkEmail'])->name('check.email');
Route::get('changePassword',[AuthController::class, 'changePassword'])->name('change.password');
Route::put('do-changePassword',[AuthController::class, 'doChangePassword'])->name('do.change.password');

Route::delete('requests/delete/{id}', [RequestController::class,'delete'])->name('delete.request')->middleware(['auth']);
Route::resource('requests', RequestController::class)->middleware(['auth']);

Route::prefix('dashboard')->middleware(['auth','first.login'])->group(function () {
    Route::get('/',[AuthController::class, 'index'])->name('dashboard');
    Route::get('Danh-sach-nhan-vien', [UserController::class, 'list'])->name('users.list');
    Route::get('Danh-sach-nhan-vien/{id}', [UserController::class, 'infomation'])->name('users.info');
    Route::get('user-view-product', [ProductController::class, 'userView'])->name('user.view.product');
    Route::get('user-list-request', [RequestController::class, 'userList'])->name('user.list.request');
    Route::put('request-solved', [RequestController::class, 'requestSolved'])->name('request.solved');
    Route::put('request-export', [RequestController::class, 'requestExport'])->name('request.export');
    Route::put('request-return', [RequestController::class, 'requestReturn'])->name('request.return');
    Route::put('do-export', [RequestController::class, 'doExport'])->name('do.export');
    Route::put('do-return', [RequestController::class, 'doReturn'])->name('do.return');
    Route::put('request-refuse', [RequestController::class, 'requestRefuse'])->name('request.refuse');
    Route::resource('products', ProductController::class);
    Route::middleware(['can:is-admin'])->group(function () {
        Route::resource('categories', CategoryController::class);
        Route::resource('users', UserController::class);
        Route::resource('departments', DepartmentController::class);
        Route::resource('roles', RoleController::class);
        Route::resource('permisstions', PermisstionController::class)->only(['index', 'create' , 'store', 'destroy']);
        Route::resource('history-requestModels', HistoryRequestModel::class)->names('history.requests');
    }); 
});

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CategoryStoreRequest;
use App\Http\Requests\CategoryUpdateRequest;
use App\Models\CategoryModel;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    private $category;
    public function __construct(CategoryModel $category)
    {
        $this->category = $category;
    }

    public function index()
    {
        $this->authorize('category.index');
        $categories = $this->category->list();
        return view('admin.categories.index',[
            'title' => 'List Category',
            'topTitle' => 'Danh sách Category ('.$categories->count().')',
            'categories' => $categories
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create',[
            'title' => 'Create Category',
            'topTitle' => 'Tạo Danh mục',
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryStoreRequest $request)
    {
        $this->category->createCate($request);
        return redirect()->back()->with('success', 'Thêm thành công danh mục :'. $request->name);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = $this->category->find($id);
        return view('admin.categories.update',[
            'title' => 'Edit Category',
            'topTitle' => 'Sửa danh mục',
            'category' => $category
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryUpdateRequest $request,$id)
    {
        $this->category->updateCate($request, $id);
        return redirect(route('categories.index'))->with('success', 'Sửa thành công danh mục:'. $request->name);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       $delete =  $this->category->deleteCategory($id);
        if($delete){
            return redirect()->back()->with('success', 'Đã xóa thành công');
        }
        return redirect()->back()->with('error', 'Có lỗi, Vui lòng liên hệ với quan trị viên');
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.main')
@section('css')
@endsection
@section('js')
@endsection
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
    <li class="breadcrumb-item "><a href="{{ route('categories.index') }}">Danh sách danh mục</a></li>
    <li class="breadcrumb-item active">Tạo danh mục </li>
@endsection
@section('content')
    <div class="col-12 box-bety">
        @include('admin.layouts.alert')
        <form action="{{ route('categories.store') }}" method="post">
            @csrf
            <div class="form-group">
                @include('admin.components.label_form', [
                    'label' => 'Tên danh mục ',
                    'name' => 'name',
                    'placeholder' => 'Mời bạn nhập tên danh mục ...',
                    'value' => old('name'),
                ])
            </div>
            <button type="submit" class="btn btn-sm btn-primary">Thêm Danh mục</button>
        </form>
    </div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.main')
@section('css')
@endsection
@section('js')
@endsection
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
    <li class="breadcrumb-item"><a href="{{ route('categories.index') }}">List Products</a></li>
@endsection
@section('content')
    <div class="col-12 box-bety">
        @can('category.create')
            <a href="{{ route('categories.create') }}" class="btn button btn-sm btn-primary" style="float: right">Thêm Danh mục</a>
        @endcan
        <span class="col-10">
        @include('admin.layouts.alert')</span>
        <table class="table table-light table-hover">
            <thead class="thead-light">
                <tr>
                    <th width=5%>STT</th>
                    <th>Tên danh mục</th>
                    <th style="text-align: center">Số lượng Thực tế</th>
                    <th style="text-align: center">Số lượng Trong kho</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($categories as $key => $category)
                    <tr>
                        <td>{{ $key + 1 }}</td>
                        <td><a href="{{ route('products.index') }}?category={{ $category->id }}">{{ $category->name }}</a>
                        </td>
                        <td style="text-align: center">{{ $category->products->count() }}</td>
                        <td style="text-align: center">{{ $category->products()->where('status', warehouse)->count() }}</td>
                        <td>
                            <div class="row">
                                @can('category.update')
                                    <a href="{{ route('categories.edit', $category->id) }}" class="button btn btn-warning"><i
                                            class="fa fa-edit"></i></a> &ensp;
                                @endcan
                                @can('category.delete')
                                    <form action="{{ route('categories.destroy', $category->id) }}" method="post">
                                        @csrf
                                        @method('delete')
                                        <button type="submit" class="button btn btn-danger" onclick="return confirm('Are you sure?')">
                                            <i class="fa fa-trash"></i></button>
                                    </form>
                                @endcan


                            </div>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
@endsection

resources/views/admin/categories/update.blade.php
@extends('admin.layouts.main')
@section('css')
@endsection
@section('js')
@endsection
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
    <li class="breadcrumb-item "><a href="{{ route('categories.index') }}">Danh sách danh mục</a></li>
    <li class="breadcrumb-item active">Sửa danh mục</li>
@endsection
@section('content')
    <div class="col-12 box-bety">
        @include('admin.layouts.alert')
        <form action="{{ route('categories.update', $category->id) }}" method="post">
            @csrf
            @method('put')
            
            <div class="form-group">
                @include('admin.components.input',[
                    'type' => 'hidden',
                    'name' => 'id',
                    'value' => $category->id
                ])
                @include('admin.components.label_form', [
                    'label' => 'Tên danh mục ',
                    'name' => 'name',
                    'placeholder' => 'Mời bạn nhập tên danh mục ...',
                    'value' => $category->name,
                ])
            </div>
            <button type="submit" class="btn btn-sm btn-primary">Sửa Danh mục</button>
        </form>
    </div>
@endsection